version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:80" # Пробрасываем порт 8080 на локальную машину к порту 80 в контейнере
    volumes:
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./app/:/var/www/html